language: go

go:
 - 1.3.1
 - tip

matrix:
  fast_finish: true

env:
  global:
    secure: hHPi/d+ob6oFvbGOfpfFgm2hvytx4S6+lby/8co0dDm/Tm7bmGUlt3BG5zcUqLq3b9Knnv1n7lAbMzBLjY+THg7RHMWNkA6OeM72MMjE4Kptq/XZUKVFJkTTFhBC7PTTMI5RDHkPStOv1AEIGpp0QtiHIkDZj5PtLrw+U0rWJEQ=

install:
 - export GOBIN=$HOME/bin
 - export PATH=$GOBIN:$PATH
 - go get code.google.com/p/go.tools/cmd/vet code.google.com/p/go.tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover
 - go get -t -v ./...
 - go install -a -race std

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
 - go list -f '{{if len .TestGoFiles}}go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}{{end}}' ./... | xargs -i sh -c {}
 - gover
 - goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
